Repository GIScience/ohsome-api, pull requests merged in 2020-08, with the labels that each got.

#29 addition of parameter ‘unclipped’
  docs/endpoints.rst
  src/main/java/org/heigit/ohsome/ohsomeapi/config/SwaggerConfig.java
  src/main/java/org/heigit/ohsome/ohsomeapi/controller/ParameterDescriptions.java
  src/main/java/org/heigit/ohsome/ohsomeapi/executor/ElementsRequestExecutor.java
  src/main/java/org/heigit/ohsome/ohsomeapi/executor/ExecutionUtils.java
  src/main/java/org/heigit/ohsome/ohsomeapi/inputprocessing/InputProcessor.java
  src/main/java/org/heigit/ohsome/ohsomeapi/inputprocessing/ResourceParameters.java
  src/test/java/org/heigit/ohsome/ohsomeapi/controller/ElementsControllerTest.java
Labels: documentation, enhancement

#39 Add additional informational badges to README
  README.md
Labels: documentation, enhancement

#38 upgrade filter library to version 1.2
  docs/filter.rst
  pom.xml
Labels: enhancement, upstream

#42 fix typo in docs
  docs/endpoints.rst
Labels: documentation
