Repository GIScience/ohsome-api, pull requests merged in 2020-11, with the labels that each got.

#75 Extract flatMap lambda functions from DataRequestExecutor
  CHANGELOG.md
  src/main/java/org/heigit/ohsome/ohsomeapi/executor/DataRequestExecutor.java
  src/main/java/org/heigit/ohsome/ohsomeapi/executor/FlatMapExecutor.java
Labels: bug

#79 release notes for patch version 1.2.2
  CHANGELOG.md
  README.md
  docs/endpoints.rst
Labels: documentation

#81 release notes for regression/bug fix version 1.2.3
  CHANGELOG.md
  README.md
  docs/endpoints.rst
Labels: documentation

#82 checkstyle: break some too long lines and add newline after static imports
  src/main/java/org/heigit/ohsome/ohsomeapi/controller/dataaggregation/AreaController.java
  src/main/java/org/heigit/ohsome/ohsomeapi/executor/ExecutionUtils.java
  src/test/java/org/heigit/ohsome/ohsomeapi/controller/GetControllerTest.java
  src/test/java/org/heigit/ohsome/ohsomeapi/controller/PostControllerTest.java
Labels: code quality
