Repository GIScience/ohsome-api, pull requests merged in 2021-06, with the labels that each got.

#206 add release notes for 1.4.2, add missing link to issue 200 and sort referenced issues
  CHANGELOG.md
  README.md
  docs/endpoints.rst
Labels: documentation

#168 swagger tweaks: reordering and remove deprecated parameters
  CHANGELOG.md
  src/main/lombok/org/heigit/ohsome/ohsomeapi/config/SwaggerConfig.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/ParameterDescriptions.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/dataaggregation/elements/AreaController.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/dataaggregation/elements/CountController.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/dataaggregation/elements/LengthController.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/dataaggregation/elements/PerimeterController.java
Labels: documentation, waiting for review

#198 Contributions latest count endpoints
  CHANGELOG.md
  docs/_static/ohsome-api-tree.svg
  docs/_static/ohsome-api-tree.txt
  docs/endpoints.rst
  src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/ParameterDescriptions.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/dataaggregation/contributions/ContributionsCountController.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/dataaggregation/users/UsersController.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/AggregateRequestExecutor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/ContributionsExecutor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/DataExtractionTransformer.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/ResourceParameters.java
  src/test/java/org/heigit/ohsome/ohsomeapi/controller/GetControllerTest.java
Labels: enhancement
