Repository GIScience/ohsome-api, pull requests merged in 2021-09, with the labels that each got.

#232 Add note about the end timestamp of period notation
  docs/time.rst
Labels: documentation

#233 Error message for requests without defined parameters
  CHANGELOG.md
  src/main/lombok/org/heigit/ohsome/ohsomeapi/exception/ExceptionMessages.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/InputProcessor.java
  src/test/java/org/heigit/ohsome/ohsomeapi/controller/PostControllerTest.java
Labels: enhancement, waiting for review

#234 add @contributionChangesetId to example output
  docs/endpoints.rst
Labels: documentation

#237 upgrade to oshdb version 0.7.2 + release as 1.6.1
  CHANGELOG.md
  README.md
  docs/endpoints.rst
  pom.xml
Labels: dependencies

#238 Jenkins: update dependency cache when building
  Jenkinsfile
Labels: CI

#239 Fix checkstyle warning about annotation order
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/ElementsRequestExecutor.java
Labels: code quality

#236 Add contributionType parameter to /users endpoints
  CHANGELOG.md
  docs/endpoints.rst
  src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/ParameterDescriptions.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/dataaggregation/users/UsersController.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/ContributionsExecutor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/ExecutionUtils.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/UsersRequestExecutor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/ResourceParameters.java
  src/test/java/org/heigit/ohsome/ohsomeapi/controller/DataExtractionTest.java
  src/test/java/org/heigit/ohsome/ohsomeapi/controller/GetControllerTest.java
  src/test/java/org/heigit/ohsome/ohsomeapi/executor/ContributionsExecutorTest.java
Labels: enhancement

#240 Docs: update link to oshdb-filter
  docs/filter.rst
Labels: documentation
