Repository GIScience/ohsome-api, pull requests merged in 2021-08, with the labels that each got.

#161 avoid unneccessary geometry building during count/ratio requests
  CHANGELOG.md
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/AggregateRequestExecutor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/ElementsRequestExecutor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/ExecutionUtils.java
Labels: enhancement

#225 upgrade to OSHDB 0.7.1
  CHANGELOG.md
  pom.xml
Labels: dependencies, priority:high

#228 fix non-unique-parameter check for post request
  CHANGELOG.md
  pom.xml
  src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/InputProcessor.java
  src/test/java/org/heigit/ohsome/ohsomeapi/controller/GetControllerTest.java
  src/test/java/org/heigit/ohsome/ohsomeapi/controller/PostControllerTest.java
Labels: bug

#229 Fix sonarlint bugs
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/ElementsRequestExecutor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/ExecutionUtils.java
Labels: code quality
