Repository GIScience/ohsome-api, pull requests merged in 2021-01, with the labels that each got.

#86 upgrade OSHDB to version 0.6
  .idea/checkstyle-idea.xml
  CHANGELOG.md
  README.md
  pom.xml
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/AggregateRequestExecutor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/DataExtractionTransformer.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/DataRequestExecutor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/ElementsRequestExecutor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/ExecutionUtils.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/UsersRequestExecutor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/InputProcessingUtils.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/InputProcessor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/ProcessingData.java
  src/test/java/org/heigit/ohsome/ohsomeapi/controller/GetControllerTest.java
  src/test/java/org/heigit/ohsome/ohsomeapi/controller/PostControllerTest.java
  src/test/java/org/heigit/ohsome/ohsomeapi/controller/TestProperties.java
Labels: dependencies

#93 Changelog: move links and add links for commits
  CHANGELOG.md
Labels: documentation

#94 minor styling fixes in CHANGELOG and docs
  CHANGELOG.md
  docs/http-response-status.rst
  docs/time.rst
Labels: documentation

#96 Fix OSHDB version
  CHANGELOG.md
Labels: documentation

#102 fix filter parameter not set when using groupBy/boundary requests
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/AggregateRequestExecutor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/ElementsRequestExecutor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/UsersRequestExecutor.java
Labels: bug

#97 make sure groupByEntity is called before filters are set
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/DataRequestExecutor.java
Labels: bug

#104 upgrade OSHDB to 0.6.3, release as 1.3.2
  CHANGELOG.md
  pom.xml
Labels: bug, dependencies

#105 update documentation to 1.3.2 release
  README.md
  docs/endpoints.rst
Labels: documentation
