Repository GIScience/ohsome-api, pull requests merged in 2021-07, with the labels that each got.

#213 CHANGELOG: remove unnecessary heading
  CHANGELOG.md
Labels: documentation

#211 Throw an exception for `bpolys` and `bcircles` boundaries lying outside the underlying data-extract polygon
  CHANGELOG.md
  src/main/lombok/org/heigit/ohsome/ohsomeapi/exception/ExceptionMessages.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/DataRequestExecutor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/GeometryBuilder.java
  src/test/java/org/heigit/ohsome/ohsomeapi/controller/PostControllerTest.java
Labels: bug

#218 Jenkins: remove infer
  Jenkinsfile
Labels: CI

#215 Catch and throw new `BadRequestException` in cases of invalid `bpolys` boundary
  CHANGELOG.md
  src/main/lombok/org/heigit/ohsome/ohsomeapi/exception/ExceptionMessages.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/GeometryBuilder.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/InputProcessor.java
  src/test/java/org/heigit/ohsome/ohsomeapi/controller/PostControllerTest.java
Labels: comments welcome, waiting for review

#221 update ohsome-parent to version 2.12.1
  .idea/checkstyle-idea.xml
  pom.xml
Labels: dependencies

#222 upgade to OSHDB version 0.7.0
  CHANGELOG.md
  Jenkinsfile
  README.md
  pom.xml
  src/main/lombok/org/heigit/ohsome/ohsomeapi/Application.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/exception/CustomizedExceptionHandler.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/AggregateRequestExecutor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/ContributionsExecutor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/DataExtractionTransformer.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/DataRequestExecutor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/ElementsRequestExecutor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/ExecutionUtils.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/UsersRequestExecutor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/GeometryBuilder.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/InputProcessingUtils.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/InputProcessor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/ProcessingData.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/oshdb/DbConnData.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/oshdb/RemoteTagTranslator.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/utils/RequestUtils.java
  src/main/resources/application.properties
  src/test/java/org/heigit/ohsome/ohsomeapi/controller/DataExtractionTest.java
Labels: dependencies

#223 Change link to OSHDB extract generation
  README.md
Labels: documentation
