Repository GIScience/ohsome-api, pull requests merged in 2021-04, with the labels that each got.

#171 add info regarding "NaN" ratio to docs
  CHANGELOG.md
  docs/endpoints.rst
Labels: documentation, waiting for review

#172 clarify note about "NaN" values in ratio results
  docs/endpoints.rst
Labels: documentation

#173 fix code style issues introduced in PRs #162 and #121
  src/main/lombok/org/heigit/ohsome/ohsomeapi/config/TomcatConfig.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/ParameterDescriptions.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/AggregateRequestExecutor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/DataExtractionTransformer.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/DataRequestExecutor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/ElementsRequestExecutor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/ExecutionUtils.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/ResourceParameters.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/output/groupby/GroupByObject.java
  src/test/java/org/heigit/ohsome/ohsomeapi/controller/DataExtractionTest.java
Labels: code quality, waiting for review

#164 better handling of geojson parsing exceptions
  CHANGELOG.md
  src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/GeometryBuilder.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/InputProcessingUtils.java
  src/test/java/org/heigit/ohsome/ohsomeapi/controller/DataExtractionTest.java
  src/test/java/org/heigit/ohsome/ohsomeapi/controller/GetControllerTest.java
  src/test/java/org/heigit/ohsome/ohsomeapi/controller/PostControllerTest.java
  src/test/java/org/heigit/ohsome/ohsomeapi/inputprocessing/GeometryBuilderTest.java
Labels: bug

#176 fix failing getMetadataTest
  CHANGELOG.md
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/MetadataRequestExecutor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/oshdb/ExtractMetadata.java
Labels: CI, bug

#177 Reformulated note in Readme
  README.md
Labels: documentation

#179 configure sonarcloud
  Jenkinsfile
  pom.xml
Labels: CI, code quality

#180 add missing setting for lombok sources directory for sonarlint
  pom.xml
Labels: CI, bug

#181 add SonarCloud Badge to Readme
  README.md
Labels: documentation
