Repository GIScience/ohsome-api, pull requests merged in 2021-05, with the labels that each got.

#184 update to ohsome-parent 2.10
  .idea/checkstyle-idea.xml
  CHANGELOG.md
  Jenkinsfile
  pom.xml
Labels: CI, dependencies

#186 update to ohsome-parent 2.11
  .gitignore
  .idea/checkstyle-idea.xml
  Jenkinsfile
  pom.xml
Labels: CI, code quality

#187 fix trailing whitespace and a few other code style issues
  src/main/lombok/org/heigit/ohsome/ohsomeapi/Application.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/config/JacksonConfig.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/config/TomcatConfig.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/DefaultSwaggerParameters.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/dataaggregation/contributions/ContributionsCountController.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/dataaggregation/elements/AreaController.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/dataaggregation/elements/CountController.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/dataaggregation/elements/LengthController.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/dataaggregation/elements/PerimeterController.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/dataaggregation/users/UsersController.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/dataextraction/contributions/ContributionsController.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/dataextraction/elements/ElementsController.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/dataextraction/elements/ElementsFullHistoryController.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/metadata/MetadataController.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/AggregateRequestExecutor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/ContributionsExecutor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/DataRequestExecutor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/ElementsRequestExecutor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/ExecutionUtils.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/MetadataRequestExecutor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/UsersRequestExecutor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/GeometryBuilder.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/InputProcessingUtils.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/InputProcessor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/ResourceParameters.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/StringSimilarity.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/output/Description.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/output/contributions/ContributionsResult.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/output/elements/ElementsResult.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/output/groupby/GroupByResponse.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/output/groupby/GroupByResult.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/output/ratio/RatioGroupByBoundaryResponse.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/utils/RequestUtils.java
  src/test/java/org/heigit/ohsome/ohsomeapi/controller/DataExtractionTest.java
  src/test/java/org/heigit/ohsome/ohsomeapi/controller/PostControllerTest.java
  src/test/java/org/heigit/ohsome/ohsomeapi/inputprocessing/GeometryBuilderTest.java
Labels: code quality

#189 change downloads links in documentation
  README.md
Labels: documentation

#183 Client list
  README.md
Labels: documentation

#178 Refactor dataextractiontransformer
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/ContributionsExecutor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/DataExtractionTransformer.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/DataRequestExecutor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/ElementsRequestExecutor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/ExecutionUtils.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/RequestParameters.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/UsersRequestExecutor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/GeometryBuilder.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/InputProcessingUtils.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/ProcessingData.java
Labels: code quality

#192 Remove the parameters @snapshotTimestamp and @lastEdit from full-history responses
  CHANGELOG.md
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/DataExtractionTransformer.java
Labels: bug

#195 update jenkins jacoco inclusionPattern
  Jenkinsfile
Labels: CI

#196 Changelog minor fix
  CHANGELOG.md
Labels: documentation

#194 Update documentation
  CHANGELOG.md
  docs/_static/ohsome-api-tree.svg
  docs/_static/ohsome-api-tree.txt
  docs/endpoints.rst
  docs/group-by.rst
  docs/http-response-status.rst
  docs/response-parameters.rst
Labels: documentation

#190 update oqt link in README
  README.md
Labels: documentation
