Repository GIScience/ohsome-api, pull requests merged in 2021-02, with the labels that each got.

#110 Add user survey note to README
  README.md
Labels: documentation

#106 add PR template and basic contribution guidelines
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: CI

#112 drop unused constants, fix syntax error in filter
  CHANGELOG.md
  src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/DefaultSwaggerParameters.java
Labels: bug, documentation

#116 tweak default swagger filter parameters
  CHANGELOG.md
  src/main/lombok/org/heigit/ohsome/ohsomeapi/config/SwaggerConfig.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/DefaultSwaggerParameters.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/dataaggregation/AreaController.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/dataaggregation/CountController.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/dataaggregation/LengthController.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/dataaggregation/PerimeterController.java
Labels: documentation

#127 fix (minor) typo: missing space
  docs/filter.rst
Labels: documentation, priority:low

#130 enable null geometries for deletions in /contributions
  CHANGELOG.md
  docs/endpoints.rst
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/ExecutionUtils.java
  src/test/java/org/heigit/ohsome/ohsomeapi/controller/DataExtractionTest.java
  src/test/java/org/heigit/ohsome/ohsomeapi/controller/Helper.java
Labels: bug

#128 Jenkinsfile minor fix and clean up
  Jenkinsfile
Labels: CI

#132 fix docs build in Jenkinsfile
  Jenkinsfile
Labels: CI

#133 configure checkstyle to not read generated "delombok" sources
  pom.xml
Labels: CI

#137 add some extra instructions for intellij users
  CONTRIBUTING.md
  README.md
Labels: documentation
