Repository GIScience/ohsome-api, pull requests merged in 2021-03, with the labels that each got.

#135 modify data type of contribution type
  CHANGELOG.md
  docs/endpoints.rst
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/ExecutionUtils.java
  src/test/java/org/heigit/ohsome/ohsomeapi/controller/DataExtractionTest.java
Labels: bug, waiting for review

#144 fix issue #141
  CHANGELOG.md
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/ElementsRequestExecutor.java
Labels: bug

#146 Revert "Add user survey note to README"
  README.md
Labels: waiting for review

#147 extend docs on contribution types
  CHANGELOG.md
  docs/response-parameters.rst
Labels: waiting for review

#148 Wrap lines
  CHANGELOG.md
  src/main/lombok/org/heigit/ohsome/ohsomeapi/Application.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/dataaggregation/elements/AreaController.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/dataaggregation/elements/CountController.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/dataaggregation/elements/LengthController.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/dataaggregation/elements/PerimeterController.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/dataaggregation/users/UsersController.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/dataextraction/contributions/ContributionsController.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/dataextraction/elements/ElementsController.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/dataextraction/elements/ElementsFullHistoryController.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/controller/metadata/MetadataController.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/AggregateRequestExecutor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/DataRequestExecutor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/ElementsRequestExecutor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/ExecutionUtils.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/MetadataRequestExecutor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/filter/RequestFilter.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/GeometryBuilder.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/InputProcessingUtils.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/InputProcessor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/ProcessingData.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/ResourceParameters.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/StringSimilarity.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/output/DefaultAggregationResponse.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/output/Response.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/output/Result.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/output/groupby/GroupByObject.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/output/groupby/GroupByResponse.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/output/groupby/GroupByResult.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/output/metadata/ExtractRegion.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/output/metadata/MetadataResponse.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/output/ratio/RatioGroupByBoundaryResponse.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/output/ratio/RatioGroupByResult.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/output/ratio/RatioResponse.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/utils/GroupByBoundaryGeoJsonGenerator.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/utils/RequestUtils.java
  src/test/java/org/heigit/ohsome/ohsomeapi/controller/DataExtractionTest.java
  src/test/java/org/heigit/ohsome/ohsomeapi/inputprocessing/GeometryBuilderTest.java
  src/test/java/org/heigit/ohsome/ohsomeapi/inputprocessing/InputProcessingUtilsTest.java
Labels: code quality

#151 apply geometry checks to all stages in elementsFullHistory requests
  CHANGELOG.md
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/DataExtractionTransformer.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/DataRequestExecutor.java
  src/test/java/org/heigit/ohsome/ohsomeapi/controller/DataExtractionTest.java
  src/test/java/org/heigit/ohsome/ohsomeapi/controller/GetControllerTest.java
  src/test/java/org/heigit/ohsome/ohsomeapi/controller/PostControllerTest.java
Labels: bug, waiting for review

#145 addition to fix #141
  CHANGELOG.md
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/DataExtractionTransformer.java
Labels: bug

#152 update ohsome-parent to version 2.8
  CHANGELOG.md
  Jenkinsfile
  pom.xml
Labels: CI, waiting for review

#155 add missing build for internal release
  Jenkinsfile
Labels: CI

#157 add missing clean, compile, and install goals to maven runs
  Jenkinsfile
Labels: CI

#163 Bump oshdb to version 0.6.4 and prepare 1.4.1 release notes
  CHANGELOG.md
  README.md
  docs/endpoints.rst
  pom.xml
Labels: documentation, upstream

#165 build API docs only when tagged as release or snapshot
  Jenkinsfile
Labels: CI, documentation

#169 fix error message for invalid boundary parameter
  src/main/lombok/org/heigit/ohsome/ohsomeapi/exception/ExceptionMessages.java
Labels: documentation
