Repository GIScience/ohsome-api, pull requests merged in 2023-03, with the labels that each got.

#293 Upgrade dependencies for Java 17 support
  pom.xml
Labels: dependencies

#297 Clarify what the groupBy* parameters actually do
  docs/group-by.rst
Labels: documentation

#294 fix error message when changeset filter is used in snapshot query
  CHANGELOG.md
  src/main/lombok/org/heigit/ohsome/ohsomeapi/exception/ExceptionMessages.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/executor/ElementsRequestExecutor.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/InputProcessingUtils.java
  src/main/lombok/org/heigit/ohsome/ohsomeapi/inputprocessing/InputProcessor.java
  src/test/java/org/heigit/ohsome/ohsomeapi/inputprocessing/DummyTagTranslator.java
  src/test/java/org/heigit/ohsome/ohsomeapi/inputprocessing/InputProcessingUtilsTest.java
Labels: bug, waiting for review

#299 update docs for 1.9.0, oshdb to 1.1.1
  CHANGELOG.md
  README.md
  docs/endpoints.rst
  pom.xml
Labels: documentation

#301 Update ohsome-parent to 2.13.1
  Jenkinsfile
  pom.xml
Labels: dependencies, CI
